- src/main/java/com/groupware/work/controller/WorkController.java
- src/main/resources/static/css/main-dev.css
- src/main/resources/static/css/main-hr.css
- src/main/resources/templates/include/side/main-side.html
- src/main/resources/templates/work/dev/main-dev.html
- src/main/resources/templates/work/hr/main-hr.html
> 개발 업무 페이지 생성

- src/main/resources/static/css/index.css
- src/main/resources/static/css/main-notice.css
- src/main/resources/templates/include/side/main-side.html
- src/main/resources/templates/index.html
- src/main/resources/templates/notice/main-notice.html
> todo리스트 - 진석

- src/main/resources/static/css/main-file.css
- src/main/resources/templates/file/main-file.html
> 프로젝트 구조 설계 (#1) - 다희

- src/main/java/com/groupware/work/controller/WorkController.java
- src/main/java/com/groupware/work/dev/dto/DevDTO.java
- src/main/java/com/groupware/work/dev/dto/ProjectDTO.java
- src/main/java/com/groupware/work/dev/dto/ProjectFeedDTO.java
- src/main/java/com/groupware/work/mapper/WorkMapper.java
- src/main/java/com/groupware/work/service/WorkService.java
- src/main/resources/static/css/main-dev.css
- src/main/resources/static/js/main-dev.js
- src/main/resources/templates/work/dev/main-dev.html
> 프로젝트 페이징 처리

- src/main/java/com/groupware/notice/controller/NoticeController.java
- src/main/resources/static/css/main-notice.css
- src/main/resources/static/css/todo.css
- src/main/resources/static/js/notice.js
- src/main/resources/static/js/todo.js
- src/main/resources/templates/mypage/todo.html
- src/main/resources/templates/notice/main-notice.html
- src/main/resources/templates/notice/notice-write.html
> todolist 수정중

- src/main/java/com/groupware/work/controller/WorkRestController.java
- src/main/java/com/groupware/work/mapper/WorkMapper.java
- src/main/java/com/groupware/work/service/WorkService.java
- src/main/resources/static/js/main-dev.js
- src/main/resources/templates/work/dev/main-dev.html
> 개발 페이지 구조 변경

- src/main/java/com/groupware/work/controller/WorkRestController.java
- src/main/java/com/groupware/work/dev/dto/ProjectMemberDTO.java
- src/main/java/com/groupware/work/dev/dto/ProjectTaskDTO.java
- src/main/java/com/groupware/work/mapper/WorkMapper.java
- src/main/java/com/groupware/work/service/WorkService.java
- src/main/resources/static/js/main-dev.js
- src/main/resources/templates/work/dev/main-dev.html
> 프로젝트 구조 #1 - hsj

- src/main/java/com/groupware/work/controller/WorkViewController.java
- src/main/java/com/groupware/work/dev/controller/DevController.java
- src/main/java/com/groupware/work/dev/devMapper/DevMapper.java
- src/main/java/com/groupware/work/dev/devService/DevService.java
- src/main/java/com/groupware/work/fm/controller/FmController.java
- src/main/java/com/groupware/work/fm/dto/fmMapper/FmMapper.java
- src/main/java/com/groupware/work/fm/dto/fmService/FmService.java
- src/main/java/com/groupware/work/hr/controller/HrController.java
- src/main/java/com/groupware/work/hr/hrMapper/HrMapper.java
- src/main/java/com/groupware/work/hr/hrService/HrService.java
- src/main/java/com/groupware/work/ms/controller/MsController.java
- src/main/java/com/groupware/work/ms/msMapper/MsMapper.java
- src/main/java/com/groupware/work/ms/msService/MsService.java
- src/main/java/com/groupware/work/pm/controller/PmController.java
- src/main/java/com/groupware/work/pm/pmMapper/PmMapper.java
- src/main/java/com/groupware/work/pm/pmService/PmService.java
> Work 디렉토리 구조 나눔

- src/main/java/com/groupware/work/dev/controller/DevController.java
- src/main/java/com/groupware/work/dev/dto/ProjectTaskDTO.java
- src/main/java/com/groupware/work/dev/mapper/DevMapper.java
- src/main/java/com/groupware/work/dev/service/DevService.java
- src/main/resources/static/css/main-dev.css
- src/main/resources/static/js/main-dev.js
- src/main/resources/templates/work/dev/main-dev.html
> 프로젝트 페이지 업무 상세 추가

- src/main/java/com/groupware/MainController.java
- src/main/java/com/groupware/notice/controller/NoticeController.java
- src/main/java/com/groupware/notice/dto/NoticeDTO.java
- src/main/java/com/groupware/notice/service/NoticeService.java
- src/main/resources/static/js/notice.js
- src/main/resources/templates/index.html
- src/main/resources/templates/notice/main-notice.html
> 홈, 공지사항 수정중

- src/main/java/com/groupware/work/dev/controller/DevController.java
- src/main/java/com/groupware/work/dev/dto/ProjectEditDTO.java
- src/main/java/com/groupware/work/dev/mapper/DevMapper.java
- src/main/java/com/groupware/work/dev/service/DevService.java
- src/main/resources/static/css/main-dev.css
- src/main/resources/static/js/main-dev.js
- src/main/resources/templates/work/dev/main-dev.html
> 킹받는 모달창 추가

- src/main/java/com/groupware/work/dev/controller/DevController.java
- src/main/java/com/groupware/work/dev/dto/ProjectTaskDTO.java
- src/main/java/com/groupware/work/dev/dto/ProjectUpdateRequestDTO.java
- src/main/java/com/groupware/work/dev/mapper/DevMapper.java
- src/main/java/com/groupware/work/dev/service/DevService.java
- src/main/resources/static/js/main-dev.js
> 모달...수정안됑아니ㅓ림

- src/main/java/com/groupware/work/controller/WorkViewController.java
- src/main/java/com/groupware/work/hr/controller/HrController.java
- src/main/java/com/groupware/work/hr/dto/HrEmployeeDTO.java
- src/main/java/com/groupware/work/hr/mapper/HrMapper.java
- src/main/java/com/groupware/work/hr/service/HrService.java
- src/main/resources/static/css/hr-edit.css
- src/main/resources/static/css/main-hr.css
- src/main/resources/templates/work/hr/hr-edit.html
- src/main/resources/templates/work/hr/main-hr.html
> 인사 사원 관리 설계 중(#2) - 다희

- src/main/java/com/groupware/work/controller/WorkViewController.java
- src/main/java/com/groupware/work/pm/mapper/PmMapper.java
- src/main/java/com/groupware/work/pm/service/PmService.java
- src/main/resources/static/css/main-pm.css
- src/main/resources/static/css/notice-detail.css
- src/main/resources/static/js/main-pm.js
- src/main/resources/static/js/side.js
- src/main/resources/templates/notice/notice-detail.html
- src/main/resources/templates/work/ms/main-ms.html
- src/main/resources/templates/work/pm/main-pm.html
> 기획실 페이지 만드는중

- src/main/java/com/groupware/work/controller/WorkViewController.java
- src/main/java/com/groupware/work/hr/controller/HrController.java
- src/main/java/com/groupware/work/hr/dto/HrEmplMagDTO.java
- src/main/java/com/groupware/work/hr/mapper/HrMapper.java
- src/main/java/com/groupware/work/hr/service/HrService.java
- src/main/resources/static/css/hr-edit.css
- src/main/resources/static/css/main-mypage.css
- src/main/resources/static/js/hr-edit.js
- src/main/resources/templates/file/main-file.html
- src/main/resources/templates/work/hr/hr-edit.html
- src/main/resources/templates/work/hr/hr-register.html
- src/main/resources/templates/work/hr/main-hr.html
> 인사 사원 정보 수정 설계 중(#2) - 다희

- src/main/java/com/groupware/notice/controller/NoticeController.java
- src/main/java/com/groupware/notice/dto/NoticeDTO.java
- src/main/java/com/groupware/notice/mapper/NoticeMapper.java
- src/main/java/com/groupware/notice/service/NoticeService.java
- src/main/java/com/groupware/work/controller/WorkViewController.java
- src/main/resources/static/js/side.js
- src/main/resources/templates/notice/notice-write.html
- src/main/resources/templates/work/ms/ceo.html
- src/main/resources/templates/work/ms/main-ms.html
> 프로젝트 구조(#1) - 진석

- src/main/java/com/groupware/notice/controller/NoticeController.java
- src/main/java/com/groupware/notice/dto/NoticeDTO.java
- src/main/java/com/groupware/notice/mapper/NoticeMapper.java
- src/main/java/com/groupware/work/controller/WorkViewController.java
- src/main/java/com/groupware/work/ms/mapper/MsMapper.java
- src/main/java/com/groupware/work/ms/service/MsService.java
- src/main/java/com/groupware/work/pm/controller/PmController.java
- src/main/java/com/groupware/work/pm/mapper/PmMapper.java
- src/main/java/com/groupware/work/pm/service/PmService.java
- src/main/resources/static/css/main-pm.css
- src/main/resources/static/js/main-pm.js
- src/main/resources/templates/index.html
- src/main/resources/templates/notice/main-notice.html
- src/main/resources/templates/notice/notice-detail.html
- src/main/resources/templates/notice/notice-edit.html
- src/main/resources/templates/work/ms/main-ms.html
- src/main/resources/templates/work/pm/main-pm.html
> 이것저것 뭐햇지..

- src/main/java/com/groupware/work/ceo/controller/CeoController.java
- src/main/java/com/groupware/work/ceo/dto/CeoDTO.java
- src/main/java/com/groupware/work/ceo/mapper/CeoMapper.java
- src/main/java/com/groupware/work/ceo/service/CeoService.java
- src/main/java/com/groupware/work/controller/WorkViewController.java
- src/main/resources/static/css/ceo.css
- src/main/resources/static/css/main-ms.css
- src/main/resources/static/js/ceo.js
- src/main/resources/templates/work/ceo.html
> 프로젝트 구조#1 - 진석

- src/main/java/com/groupware/user/mapper/UserMapper.java
- src/main/java/com/groupware/work/controller/WorkViewController.java
- src/main/java/com/groupware/work/hr/controller/HrController.java
- src/main/java/com/groupware/work/hr/dto/HrDTO.java
- src/main/java/com/groupware/work/hr/dto/HrEmployeeUpdateDTO.java
- src/main/java/com/groupware/work/hr/dto/HrStatusDTO.java
- src/main/java/com/groupware/work/hr/mapper/HrMapper.java
- src/main/java/com/groupware/work/hr/service/HrService.java
- src/main/resources/static/css/hr-edit.css
- src/main/resources/static/js/hr-edit.js
- src/main/resources/templates/work/hr/hr-edit.html
> 인사..거의 다 해가요..

- src/main/java/com/groupware/work/pm/controller/PmController.java
- src/main/java/com/groupware/work/pm/dto/MeetingDetailsDTO.java
- src/main/java/com/groupware/work/pm/dto/MeetingUpdateRequestDTO.java
- src/main/java/com/groupware/work/pm/mapper/PmMapper.java
- src/main/java/com/groupware/work/pm/service/PmService.java
- src/main/resources/static/js/main-pm.js
지옥의 회의 멤버 추가 수정 삭제 될겁니다... 아마?
> 지옥의 회의 멤버 추가 수정 삭제

- src/main/java/com/groupware/work/controller/WorkViewController.java
- src/main/java/com/groupware/work/hr/controller/HrController.java
- src/main/java/com/groupware/work/hr/dto/HrApprovalDTO.java
- src/main/java/com/groupware/work/hr/dto/HrStatusDTO.java
- src/main/java/com/groupware/work/hr/mapper/HrMapper.java
- src/main/java/com/groupware/work/hr/service/HrService.java
- src/main/resources/static/css/hr-edit.css
- src/main/resources/static/css/main-file.css
- src/main/resources/static/css/main-hr.css
- src/main/resources/static/js/hr-edit.js
- src/main/resources/static/js/main-file.js
- src/main/resources/static/js/main-hr.js
- src/main/resources/templates/file/main-file.html
- src/main/resources/templates/work/hr/hr-edit.html
- src/main/resources/templates/work/hr/main-hr.html
> 인사 완료했습니다..드디어..

- src/main/java/com/groupware/work/ms/mapper/MsMapper.java
- src/main/resources/static/css/header.css
- src/main/resources/static/css/hr-edit.css
- src/main/resources/static/css/index.css
- src/main/resources/static/css/main-approval.css
- src/main/resources/static/css/main-file.css
- src/main/resources/static/css/main-hr.css
- src/main/resources/static/css/main-mypage.css
- src/main/resources/static/css/main-notice.css
- src/main/resources/static/css/main-pm.css
- src/main/resources/static/css/side.css
- src/main/resources/static/css/todo.css
- src/main/resources/static/js/ceo.js
- src/main/resources/static/js/main-hr.js
- src/main/resources/static/js/main-ms.js
- src/main/resources/templates/approval/main-approval.html
- src/main/resources/templates/file/main-file.html
- src/main/resources/templates/index.html
- src/main/resources/templates/mypage/main-mypage.html
- src/main/resources/templates/mypage/todo.html
- src/main/resources/templates/notice/main-notice.html
- src/main/resources/templates/work/ceo.html
- src/main/resources/templates/work/fm/finance.html
- src/main/resources/templates/work/hr/hr-edit.html
- src/main/resources/templates/work/hr/main-hr.html
- src/main/resources/templates/work/ms/main-ms.html
- src/main/resources/templates/work/pm/main-pm.html
> css 등 구조변경

- src/main/java/com/groupware/user/controller/UserController.java
- src/main/java/com/groupware/user/dto/UserDTO.java
- src/main/java/com/groupware/user/dto/UserUpdateDTO.java
- src/main/java/com/groupware/user/mapper/UserMapper.java
- src/main/resources/static/js/hr-register.js
- src/main/resources/templates/mypage/main-mypage.html
- src/main/resources/templates/work/hr/hr-register.html
> daum 주소 api 적용

- src/main/resources/static/css/main-dev.css
- src/main/resources/templates/work/dev/main-dev.html
> dev 페이지 css 수정

- src/main/java/com/groupware/work/hr/mapper/HrMapper.java
- src/main/java/com/groupware/work/hr/service/HrService.java
> HrService에 빨간줄 수정

- src/main/java/com/groupware/file/controller/FileController.java
- src/main/java/com/groupware/file/mapper/FileMapper.java
- src/main/java/com/groupware/file/service/FileService.java
- src/main/resources/static/css/main-file.css
- src/main/resources/static/js/hr-edit.js
- src/main/resources/static/js/main-file.js
- src/main/resources/templates/file/main-file.html
> 인사 업무 수정, 파일 중복 체크

- src/main/java/com/groupware/work/controller/WorkViewController.java
- src/main/java/com/groupware/work/hr/controller/HrController.java
- src/main/java/com/groupware/work/hr/mapper/HrMapper.java
- src/main/java/com/groupware/work/hr/service/HrService.java
- src/main/resources/static/css/main-mypage.css
- src/main/resources/static/js/hr-edit.js
- src/main/resources/static/js/hr-register.js
- src/main/resources/templates/work/hr/hr-edit.html
- src/main/resources/templates/work/hr/hr-register.html
상태 변경 시 변경할 수 없는 조건 추가, 
사원등록 '취소' 버튼 css 수정
> 인사 상태변경, 사원등록 버튼 css 수정
